# Generated by Django 5.2 on 2025-04-04 23:39

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_registered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pojemność'),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(default='#003d7c', image_field=None, max_length=25, samples=None, verbose_name='Kolor w kalendarzu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('remote', 'Zdalnie'), ('in_person', 'Stacjonarnie')], default='in_person', max_length=10, verbose_name='Tryb'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=200, verbose_name='Organizator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registered',
            field=models.PositiveIntegerField(default=0, verbose_name='Zarejestrowani uczestnicy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
    ]
